export const STUDENT_LOGIN_REQUEST = "STUDENT_LOGIN_REQUEST";
export const STUDENT_LOGIN_SUCCESS = "STUDENT_LOGIN_SUCCESS";
export const STUDENT_LOGIN_FAILURE = "STUDENT_LOGIN_FAILURE";

export const TUTOR_LOGIN_REQUEST = "TUTOR_LOGIN_REQUEST";
export const TUTOR_LOGIN_SUCCESS = "TUTOR_LOGIN_SUCCESS";
export const TUTOR_LOGIN_FAILURE = "TUTOR_LOGIN_FAILURE";