export const POST_TUTOR_BOOKING_REQUEST = "POST_TUTOR_BOOKING_REQUEST"
export const POST_TUTOR_BOOKING_SUCCESS = "POST_TUTOR_BOOKING_SUCCESS"
export const POST_TUTOR_BOOKING_FAILURE = "POST_TUTOR_BOOKING_FAILURE"

export const GET_TUTOR_BOOKING_REQUEST = "GET_TUTOR_BOOKING_REQUEST"
export const GET_TUTOR_BOOKING_SUCCESS = "GET_TUTOR_BOOKING_SUCCESS"
export const GET_TUTOR_BOOKING_FAILURE = "GET_TUTOR_BOOKING_FAILURE"