export const POST_TUTOR_REQUEST = "POST_TUTOR_REQUEST"
export const POST_TUTOR_SUCCESS = "POST_TUTOR_SUCCESS"
export const POST_TUTOR_FAILURE = "POST_TUTOR_FAILURE"

export const GET_TUTOR_REQUEST = "GET_TUTOR_REQUEST"
export const GET_TUTOR_SUCCESS = "GET_TUTOR_SUCCESS"
export const GET_TUTOR_FAILURE = "GET_TUTOR_FAILURE"

export const DELETE_TUTOR_REQUEST = "DELETE_TUTOR_REQUEST"
export const DELETE_TUTOR_SUCCESS = "DELETE_TUTOR_SUCCESS"
export const DELETE_TUTOR_FAILURE = "DELETE_TUTOR_FAILURE"

export const PATCH_TUTOR_REQUEST = "PATCH_TUTOR_REQUEST"
export const PATCH_TUTOR_SUCCESS = "PATCH_TUTOR_SUCCESS"
export const PATCH_TUTOR_FAILURE = "PATCH_TUTOR_FAILURE"