export const STUDENT_REGISTER_REQUEST = "STUDENT_REGISTER_REQUEST";
export const STUDENT_REGISTER_SUCCESS = "STUDENT_REGISTER_SUCCESS";
export const STUDENT_REGISTER_FAILURE = "STUDENT_REGISTER_FAILURE";

export const TUTOR_REGISTER_REQUEST = "TUTOR_REGISTER_REQUEST";
export const TUTOR_REGISTER_SUCCESS = "TUTOR_REGISTER_SUCCESS";
export const TUTOR_REGISTER_FAILURE = "TUTOR_REGISTER_FAILURE";